domain_path: D:\Documents\Travail\ENSSAT\3A\USN\insertionSortSoftware\insertionSortVitis\platform\export\platform\sw\standalone_ps7_cortexa9_0
app_src_dir: D:\Downloads\Vitis\2023.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
